uploads = []
generated = []

[[outputs]]
id = "mhXSQjxn3x5KV8KVKOV63"
uri = "file://chexov-orders-apk.zip"
type = "unspecified"
title = "Чехов Заказы — Android APK (разархивируйте и установите)"

[[outputs]]
id = "dm2UDUKckoFxAQUV2BaFH"
uri = "file://chexov-orders-new.apk"
type = "unspecified"
title = "Чехов Заказы — APK"
